[project]
name = 'ChainChat'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
## [contracts.strategy-engine]
## path = 'contracts/strategy-engine.clar'
## clarity_version = 4
## epoch = 'latest'
## 
[contracts.strategy-vault]
path = 'contracts/strategy-vault.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-emergency]
path = 'contracts/vault-emergency.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-factory]
path = 'contracts/vault-factory.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-fee-collector]
path = 'contracts/vault-fee-collector.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-governance]
path = 'contracts/vault-governance.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-insurance]
path = 'contracts/vault-insurance.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-registry]
path = 'contracts/vault-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-rewards]
path = 'contracts/vault-rewards.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-staking]
path = 'contracts/vault-staking.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-timelock]
path = 'contracts/vault-timelock.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault-treasury]
path = 'contracts/vault-treasury.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
